### ISSUE TITLE
Finish user authentication

### ISSUE THREAD

**Issue by bhicks927** [in-StinkT/inStinkT#12]
# TODO
---
- [x] User should be able to login once and stay logged in across sessions

- [x] User should be shown a login and register button in the header if they are not currently logged in

- [x] User should be shown a logout button instead of a login button in the header if they are currently logged in

- [x] Session should be destroyed when the user logs out
